### ISSUE TITLE
Try to get url from stdin if `--url` is not provided

### ISSUE THREAD

**Issue by doronbehar** [thegeeklab/url-parser#64]
Hello!

Thanks for creating this tool! I was wondering, it'd be useful to make it read the URL from stdin so putting `url-parser` in a shell pipe would look better:

```
curl --silent $url | pup '#css-id-selector attr{href}' | url-parser path
```

Also, it's kind of weird that if no `--url` is provided, no error message is given. Moreoever, it's surprising that this doesn't work:

```
url-parser --url=... path
```

Whereas only this works:

```
url-parser path --url=...
```

**Comment by xoxys** [comment]
Thanks for your feedback. That `url-parser --url=... path` works while `url-parser --url=... path` is the result of trying to be smart :sweat_smile: `--url` is a global flag and a such the only order that should work is `url-parser --url=... path`  or to be more generic `url-parser [global options] command [command options] [arguments...]`. In general, the library is strict in how flags are handled, and the order always matters. 

Adding support for `stdin` and return an error in case of an empty URL makes sense, already working on a PR.
